version: "2.2"

services:

  pulsar:
    image: apachepulsar/pulsar:2.4.0-SNAPSHOT
    ports: 
      - 6650:6650
      - 8080:8080
    entrypoint: bin/pulsar standalone
    volumes: 
      - pulsdata:/pulsar/data

  consumer:
    image: pulsar-demo-env:dash #pulsar-key-sharing:2.4.0-SHAPSHOT 
    entrypoint: ["mvn", "exec:java", "-Dexec.mainClass=core.CollectorMain"]
    volumes: 
      - /home/ben/.m2:/home/ben/.m2/ 
      - ${PWD}:/home/ben/demo
    environment:
      SERVICE_URL: "pulsar://pulsar:6650" #"pulsar://192.168.99.100:30002";
      TOPIC: "persistent://public/default/key_shared"
      PRODUCE_TOPIC: "persistent://public/default/key_shared_stats"
      SUBSCRIPTION: "key-shared"
      SLEEP_TIME: 3000
      TIME_OUT: 0
    restart: on-failure:5
    scale: 3

  producer:
    image: pulsar-demo-env:dash
    entrypoint: ["mvn", "exec:java", "-Dexec.mainClass=core.CreatorMain"]
    volumes: 
      - /home/ben/.m2:/home/ben/.m2/ 
      - ${PWD}:/home/ben/demo
    environment:
      SERVICE_URL: "pulsar://pulsar:6650" #"pulsar://192.168.99.100:30002";
      SERVICE_HTTP_URL: "http://pulsar:8080"
      TOPIC: "persistent://public/default/key_shared"
      SUBSCRIPTION: "key-shared"
      BEFORE_START: 15000
      N_MESSAGES: 100
    restart: on-failure:5

  visualize:
    image: pulsar-demo-env:dash
    entrypoint: ["python", "-u", "dashboard/pulsar-dash/key-share-dash.py"]
    volumes:
      - ${PWD}:/home/ben/demo
    ports:
      - 8050:8050
    environment:
      SERVICE_URL: "pulsar://pulsar:6650" 
      TOPIC: "persistent://public/default/key_shared_stats"
      SUBSCRIPTION: "key-shared-stats"
      TIMEOUT: .1
      SLEEP_TIME: 5
      RETRIES: 10
      PYTHONUNBUFFERED: 0 # Allows python print to be seen from docker logs.
    restart: on-failure:5

volumes:
      pulsdata:
